export const plans = [
  {
    name: "Starter",
    planId: "starter",
    price: 250,
    stripeMonthlyPriceId: process.env.STRIPE_STARTER_PRICE_ID ?? "",
    minutes: 200,
    overagePerMinute: 0.75,
    description: "For the always-busy trades pro",
    features: [
      "200 minutes/month included",
      "Unlimited inbound calls",
      "Automatic appointment booking",
      "SMS confirmations to callers",
      "Jobber & Google Calendar sync",
      "Service area verification",
      "Lead capture & qualification",
      "Email summary reports",
    ],
    cta: "Get Started",
    highlighted: false,
  },
  {
    name: "Pro",
    planId: "pro",
    price: 350,
    stripeMonthlyPriceId: process.env.STRIPE_PRO_PRICE_ID ?? "",
    minutes: 400,
    overagePerMinute: 0.75,
    description: "For high-volume trades teams",
    features: [
      "400 minutes/month included",
      "Unlimited inbound calls",
      "Everything in Starter",
      "Priority call handling",
      "Configurable assistant name & voice",
      "Team member access",
      "Dedicated onboarding support",
      "Usage analytics dashboard",
    ],
    cta: "Get Started",
    highlighted: true,
  },
]
