name: Verify Content

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.14.1
          cache: npm

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Verify content
        run: npm run verify:content
